from contextlib import redirect_stdout, redirect_stderr
from copy import deepcopy
from datetime import timedelta
import io
import json
from pathlib import Path
import shutil
import unittest

import numpy as np
from scipy.optimize import check_grad
from scipy.special import softmax

from rival.commands import main
from rival.integrity import IntegrityError
from rival.mathx import canonical_hash
from rival.qualification_baselines import (fit_baselines, objective_gradient,
    predict_baselines, summarize_sample)
from rival.qualification_catalog import QualificationCatalog
from rival.qualification_contract import QualificationProtocol
from rival.qualification_report import build_assessment, design_feasibility
from rival.schemas import utc_now
from rival.study_workflow import _workspace, run_study
import test_runtime_uncertainty as uq_helpers


BASELINE_SETTINGS = {"feature_names": ["price_level"], "feature_provenance": "Generated outcome-free price",
                     "relevance": "Generated fixture only; a real study must justify its baseline features"}


def member(identifier):
    anchors = [canonical_hash(identifier + "-anchor-" + str(i)) for i in range(4)]
    outcomes = [canonical_hash(identifier + "-evaluation-" + str(i)) for i in range(4)]
    return {"study_id": identifier, "features": [1.0], "source_reference": "Generated fixture " + identifier,
        "instrument_sha256": canonical_hash(identifier + "-instrument"), "rights_reference": "Generated by Rival",
        "evidence_origin": "generated", "outcome_access": "inspected", "timing": "historical",
        "fieldwork_starts_at": "2026-01-01T00:00:00+00:00", "outcomes_available_at": "2026-01-02T00:00:00+00:00",
        "independence_rationale": "Generated software cases, not independent human evidence",
        "anchor_units": anchors, "evaluation_units": outcomes, "unit_weights": {u: 1.0 for u in anchors + outcomes}}


def protocol(identifiers):
    return {"study_family": "Generated delivery preference questions", "audience": "Generated audience",
        "geography": ["US"], "intended_decision": "Test software gates only",
        "threshold_rationale": "Generated test settings, not a proposed business tolerance",
        "subgroup_scope": "Aggregate fixture only; no subgroup claim", "max_tvd": 0.4,
        "minimum_baseline_improvement": 0.01, "required_coverage": 0.8, "minimum_acceptance_rate": 0.1,
        "max_bad_acceptance_rate": 0.1, "max_failure_rate": 0.1, "max_missing_rate": 0.3,
        "budget_per_study_usd": 4.0, "human_unit_cost_usd": 1.0, "max_turnaround_seconds": 3600.0,
        "members": [member(i) for i in identifiers]}


def sample(spec, role="evaluation", choices=("standard", "flexible", "flexible", "neither")):
    return {"source_reference": spec["source_reference"], "rows": [
        {"unit_sha256": unit, "choice_id": choice, "weight": spec["unit_weights"][unit]}
        for unit, choice in zip(spec[role + "_units"], choices, strict=True)]}


OPERATIONS = {"candidate_other_cost_usd": 1.0, "human_only_total_cost_usd": 4.0,
              "human_only_turnaround_seconds": 60.0, "receipt_reference": "Generated cost receipt"}


class BaselineNumericsTests(unittest.TestCase):
    def test_tiny_roster_cannot_pass_even_with_perfect_outcomes(self):
        self.assertFalse(design_feasibility(protocol(["a", "b", "c", "d"]))["statistical_gates_possible"])
        self.assertTrue(design_feasibility(protocol([str(i) for i in range(512)]))["statistical_gates_possible"])

    def test_multinomial_gradient_matches_independent_finite_differences(self):
        rng = np.random.default_rng(56)
        design = np.column_stack((np.ones(9), rng.normal(size=(9, 2))))
        outcomes = rng.dirichlet([1, 2, 3], 9)
        weights = np.arange(1, 10) / 45
        theta = rng.normal(size=9)
        error = check_grad(lambda t: objective_gradient(t, design, outcomes, weights, 0.1)[0],
                           lambda t: objective_gradient(t, design, outcomes, weights, 0.1)[1], theta)
        self.assertLess(error, 2e-6)

    def test_constant_features_match_weighted_history(self):
        outcomes = [[0.2, 0.3, 0.5], [0.8, 0.1, 0.1], [0.1, 0.6, 0.3]]
        fit = fit_baselines([[1.0]] * 3, outcomes, [1., 2., 3.], BASELINE_SETTINGS)
        expected = np.average(outcomes, axis=0, weights=[1, 2, 3])
        prediction = predict_baselines(fit, [1.])
        np.testing.assert_allclose(prediction["weighted_history"], expected, atol=1e-12)
        np.testing.assert_allclose(prediction["classical_multinomial"], expected, atol=1e-10)
        self.assertTrue(fit["diagnostics"]["converged"])

    def test_classical_model_recovers_feature_signal_and_does_not_refit_on_prediction(self):
        x = np.linspace(-2, 2, 60)
        y = softmax(np.column_stack((2*x, -x, np.zeros(len(x)))), axis=1)
        fit = fit_baselines([[float(v)] for v in x], y, [1.] * len(x), {**BASELINE_SETTINGS, "ridge": 1e-5})
        before = canonical_hash(fit)
        prediction = predict_baselines(fit, [0.5])
        np.testing.assert_allclose(prediction["classical_multinomial"], softmax([1., -0.5, 0.]), atol=2e-4)
        self.assertEqual(before, canonical_hash(fit))
        self.assertGreater(np.max(np.abs(np.asarray(prediction["weighted_history"]) - prediction["classical_multinomial"])), 0.1)
        with self.assertRaises(ValueError):
            predict_baselines(fit, [1.7e308])

    def test_invalid_features_weights_and_nonconvergence_are_visible(self):
        for features, weights in (([[True]] * 3, [1.] * 3), ([[float("nan")]] * 3, [1.] * 3),
                                  ([[1.]] * 3, [1., -1., 1.]), ([[1.]] * 3, [1., True, 1.])):
            with self.assertRaises(ValueError):
                fit_baselines(features, [[0.2, 0.8]] * 3, weights, BASELINE_SETTINGS)
        fit = fit_baselines([[-2.], [0.], [2.]], [[0.9, 0.1], [0.3, 0.7], [0.1, 0.9]], [1.] * 3,
            {**BASELINE_SETTINGS, "max_iter": 1, "ridge": 1e-5})
        self.assertFalse(fit["diagnostics"]["converged"])

    def test_missing_response_denominators_and_frozen_weights(self):
        spec = member("sample")
        data = sample(spec, choices=("standard", None, "flexible", "neither"))
        summary = summarize_sample(data, spec["evaluation_units"], ["standard", "flexible", "neither"], spec["unit_weights"])
        self.assertEqual((summary["eligible_units"], summary["observed_units"], summary["missing_units"]), (4, 3, 1))
        self.assertEqual(summary["missing_weight_fraction"], 0.25)
        self.assertEqual(summary["distribution"], [1/3] * 3)
        self.assertEqual(summary["effective_observed_units"], 3.)
        for mutation in (lambda d: d["rows"].pop(), lambda d: d["rows"].append(d["rows"][0]),
                         lambda d: d["rows"][0].update(weight=2.), lambda d: d["rows"][0].update(choice_id="other")):
            changed = deepcopy(data)
            mutation(changed)
            with self.assertRaises(ValueError):
                summarize_sample(changed, spec["evaluation_units"], ["standard", "flexible", "neither"], spec["unit_weights"])

    def test_protocol_rejects_sample_overlap_quota_changes_and_invalid_dates(self):
        original = protocol(["a", "b"])
        QualificationProtocol.model_validate(original)
        for mutation in (lambda p: p["members"][1].update(anchor_units=p["members"][0]["anchor_units"]),
                         lambda p: p.update(budget_per_study_usd=5.0),
                         lambda p: p["members"][0].update(outcomes_available_at="2026-01-02T00:00:00"),
                         lambda p: p.update(max_tvd=True), lambda p: p.update(minimum_historical_groups=2)):
            changed = deepcopy(original)
            mutation(changed)
            with self.assertRaises(ValueError):
                QualificationProtocol.model_validate(changed)


class QualificationGateTests(unittest.TestCase):
    def fixture(self):
        specs = protocol([str(i) for i in range(512)])
        plan = {"protocol": specs, "baselines_sha256": canonical_hash("baselines"), "pins": {"fixture": True}}
        baseline = {"model": {"diagnostics": {"converged": True}}}
        rows = []
        for spec in specs["members"]:
            summary = summarize_sample(sample(spec), spec["evaluation_units"], ["standard", "flexible", "neither"])
            rows.append({"study_id": spec["study_id"], "accounting": {"total_cost_usd": 0., "known_cost_usd": 0.},
                "prediction": {"candidate": [0.3, 0.5, 0.2], "baselines": {name: [0.8, 0.1, 0.1]
                    for name in ("synthetic_only", "weighted_history", "classical_multinomial", "human_only")},
                    "uncertainty": {"upper_tvd": 0.1, "candidate_accept": True}, "anchor_summary": summary},
                "observed": [0.25, 0.5, 0.25], "human_sample": summary, "operation": OPERATIONS,
                "candidate_turnaround_seconds": 10., "prospective_timing_verified": False,
                "outcome_evidence_sha256": canonical_hash("generated-outcomes")})
        return plan, baseline, rows

    def test_statistical_success_cannot_turn_generated_evidence_into_human_qualification(self):
        plan, baseline, rows = self.fixture()
        report = build_assessment(plan, baseline, rows)
        for name in ("absolute_error", "coverage", "acceptance_rate", "accepted_error_risk", "failure_rate"):
            self.assertTrue(report["gates"][name])
        self.assertTrue(all(report["gates"]["improvement_over_" + name] for name in report["baseline_comparisons"]))
        self.assertFalse(report["gates"]["untouched_historical_evidence"])
        self.assertFalse(report["customer_qualified"])

    def test_distribution_shift_fails_coverage_and_accepted_risk_without_refitting(self):
        plan, baseline, rows = self.fixture()
        before = canonical_hash([r["prediction"] for r in rows])
        for row in rows:
            row["observed"] = [1., 0., 0.]
        report = build_assessment(plan, baseline, rows)
        self.assertFalse(report["gates"]["absolute_error"])
        self.assertFalse(report["gates"]["coverage"])
        self.assertFalse(report["gates"]["accepted_error_risk"])
        self.assertEqual(report["bad_accepted_groups"], 512)
        self.assertEqual(before, canonical_hash([r["prediction"] for r in rows]))

    def test_missing_outcomes_for_accepted_studies_count_as_bad_acceptances(self):
        plan, baseline, rows = self.fixture()
        for row in rows[:80]:
            row["failure"] = "missing_protected_outcome"
        report = build_assessment(plan, baseline, rows)
        self.assertEqual((report["planned_groups"], report["accepted_groups"], report["bad_accepted_groups"]), (512, 512, 80))
        self.assertEqual(report["failed_groups"], 80)
        self.assertFalse(report["gates"]["failure_rate"])
        self.assertFalse(report["gates"]["accepted_error_risk"])

    def test_missing_human_weight_mass_and_operating_overrun_fail_their_gates(self):
        plan, baseline, rows = self.fixture()
        for row in rows:
            row["human_sample"] = {**row["human_sample"], "missing_weight_fraction": 0.5}
            row["operation"] = {**OPERATIONS, "candidate_other_cost_usd": 5.}
        report = build_assessment(plan, baseline, rows)
        self.assertFalse(report["gates"]["missingness"])
        self.assertFalse(report["gates"]["absolute_error"])
        self.assertFalse(report["gates"]["operating_cost_and_time"])
        self.assertLess(report["baseline_comparisons"]["human_only"]["conservative_mean_improvement"], 0)


class QualificationWorkflowTests(unittest.TestCase):
    def setUp(self):
        self.case = uq_helpers.UncertaintyWorkflowTests(methodName="runTest")
        self.case.setUp()
        self.addCleanup(self.case.doCleanups)
        self.catalog = QualificationCatalog(self.case.root / "qualification")
        roots = self.case.training(("classical-a", "classical-b", "classical-c"))
        self.fit = self.catalog.fit(roots, [{"study_id": r.name, "features": [float(i)], "weight": 1.}
                                   for i, r in enumerate(roots)], BASELINE_SETTINGS)
        self.case.assessment(calibrated=True)
        self.roots = [self.case.prepare_target(self.case.target("qual-" + str(i))) for i in range(3)]
        self.protocol = protocol([r.name for r in self.roots])
        self.protocol.update(audience=self.case.request.audience.description, geography=self.case.request.audience.geography)

    def plan(self):
        self.planned = self.catalog.plan(self.roots, self.protocol, self.fit["baselines_sha256"])
        return self.planned["plan_sha256"]

    def finish(self, count=3):
        outcome, operation = {}, {}
        for spec, root in zip(self.protocol["members"][:count], self.roots[:count], strict=True):
            self.case.execute(root)
            self.catalog.seal(self.planned["plan_sha256"], root, sample(spec, "anchor"))
            self.case.evaluate(root)
            outcome[root.name] = sample(spec)
            operation[root.name] = OPERATIONS
        return outcome, operation

    def test_full_workflow_reproduces_protected_results_and_never_claims_fixture_qualification(self):
        plan = self.plan()
        outcome, operation = self.finish()
        record = self.catalog.assess(plan, self.roots, outcome, operation)
        assessment = self.catalog.load_assessment(record["assessment_sha256"])
        report = assessment["report"]
        self.assertEqual((report["planned_groups"], report["scored_groups"], report["failed_groups"]), (3, 3, 0))
        self.assertEqual(report["status"], "FAIL")
        self.assertFalse(report["customer_qualified"])
        self.assertFalse(report["gates"]["untouched_historical_evidence"])
        self.assertFalse(report["gates"]["improvement_over_weighted_history"])
        self.assertTrue(report["gates"]["operating_cost_and_time"])
        for row in report["rows"]:
            self.assertLess(row["candidate_tvd"], 0.01)
            self.assertGreater(row["baseline_improvement"]["synthetic_only"], 0.2)
        root = self.roots[0]
        self.assertTrue(run_study(root)["complete"])
        self.assertTrue(self.catalog.seal(plan, root, sample(self.protocol["members"][0], "anchor"))["reused"])
        self.assertEqual(self.catalog.assess(plan, [], {}, {}), record)
        with redirect_stdout(io.StringIO()) as output:
            self.assertEqual(main(["qualification", "inspect", "--catalog", str(self.catalog.root), "--assessment", record["assessment_sha256"]]), 0)
        self.assertEqual(json.loads(output.getvalue())["status"], "FAIL")

    def test_plan_is_before_execution_and_cannot_be_changed_or_reused_for_another_policy(self):
        for changed in ({**self.protocol, "geography": ["PK"]}, {**self.protocol, "audience": "A different population"}):
            with self.assertRaisesRegex(ValueError, "match the prepared"):
                self.catalog.plan(self.roots, changed, self.fit["baselines_sha256"])
        plan = self.plan()
        self.assertEqual(self.catalog.plan(self.roots[::-1], self.protocol, self.fit["baselines_sha256"])["plan_sha256"], plan)
        changed = {**self.protocol, "minimum_baseline_improvement": 0.02}
        copied = self.case.root / "another-catalog"
        shutil.copytree(self.catalog.root, copied)
        with self.assertRaises(IntegrityError):
            QualificationCatalog(copied).plan(self.roots, changed, self.fit["baselines_sha256"])
        with self.assertRaises(IntegrityError):
            self.catalog.plan(self.roots, changed, self.fit["baselines_sha256"])
        self.case.execute(self.roots[0])
        with self.assertRaisesRegex(ValueError, "before any target"):
            self.catalog.plan(self.roots, self.protocol, self.fit["baselines_sha256"])

    def test_seal_rejects_late_baselines_and_changed_human_anchors(self):
        plan = self.plan()
        self.case.execute(self.roots[0])
        self.case.evaluate(self.roots[0])
        with self.assertRaisesRegex(ValueError, "before outcome"):
            self.catalog.seal(plan, self.roots[0], sample(self.protocol["members"][0], "anchor"))
        root, spec = self.roots[1], self.protocol["members"][1]
        self.case.execute(root)
        self.catalog.seal(plan, root, sample(spec, "anchor"))
        altered = sample(spec, "anchor", ("standard",) * 4)
        with self.assertRaisesRegex(IntegrityError, "cannot replace"):
            self.catalog.seal(plan, root, altered)

    def test_incomplete_and_omitted_studies_remain_and_assessment_is_final(self):
        plan = self.plan()
        outcome, operation = self.finish(1)
        record = self.catalog.assess(plan, self.roots[:2], outcome, operation)
        report = self.catalog.load_assessment(record["assessment_sha256"])["report"]
        self.assertEqual((report["planned_groups"], report["scored_groups"], report["failed_groups"]), (3, 1, 2))
        self.assertEqual([r.get("failure") for r in report["rows"]][1:], ["incomplete_execution", "missing_workspace"])
        self.assertGreater(report["mean_missingness_adjusted_tvd"], 0.66)
        self.assertFalse(report["gates"]["failure_rate"])
        self.assertEqual(self.catalog.assess(plan, self.roots, {}, {}), record)

    def test_outcomes_must_match_exact_protected_distribution_and_frozen_weight(self):
        plan = self.plan()
        outcome, operation = self.finish()
        identifier = self.roots[0].name
        tampered = deepcopy(outcome)
        tampered[identifier]["rows"][0]["choice_id"] = "neither"
        with self.assertRaisesRegex(IntegrityError, "exact protected"):
            self.catalog.assess(plan, self.roots, tampered, operation)
        tampered = deepcopy(outcome)
        tampered[identifier]["rows"][0]["weight"] = 2.
        with self.assertRaisesRegex(ValueError, "frozen design"):
            self.catalog.assess(plan, self.roots, tampered, operation)
        self.catalog.assess(plan, self.roots, outcome, operation)

    def test_missing_costs_and_priority_subgroups_stay_unevaluable(self):
        self.protocol["priority_subgroups"] = ["priority-age-group"]
        plan = self.plan()
        outcome, _ = self.finish()
        record = self.catalog.assess(plan, self.roots, outcome, {})
        report = self.catalog.load_assessment(record["assessment_sha256"])["report"]
        self.assertIsNone(report["gates"]["operating_cost_and_time"])
        self.assertIsNone(report["gates"]["priority_subgroups"])
        self.assertIsNone(report["rows"][0]["candidate_total_cost_usd"])

    def test_historical_data_cannot_be_relabelled_as_future_fieldwork(self):
        self.protocol["members"][0]["timing"] = "prospective"
        with self.assertRaisesRegex(ValueError, "fieldwork must start after"):
            self.plan()
        self.protocol["members"][0].update(fieldwork_starts_at=(utc_now() + timedelta(days=1)).isoformat(),
            outcomes_available_at=(utc_now() + timedelta(days=2)).isoformat())
        plan = self.plan()
        outcome, operation = self.finish()
        result = self.catalog.assess(plan, self.roots, outcome, operation)
        self.assertEqual(self.catalog.load_assessment(result["assessment_sha256"])["report"]["prospective_human_groups"], 0)

    def test_cli_failure_exit_and_export_excludes_private_rosters(self):
        plan = self.plan()
        outcome, operation = self.finish(1)
        for name, value in (("outcomes", outcome), ("operations", operation)):
            (self.case.root / (name + ".json")).write_text(json.dumps(value))
        arguments = ["qualification", "assess", "--catalog", str(self.catalog.root), "--plan", plan,
                     "--outcomes", str(self.case.root / "outcomes.json"), "--operations", str(self.case.root / "operations.json")]
        for root in self.roots:
            arguments += ["--workspace", str(root)]
        with redirect_stdout(io.StringIO()) as output:
            self.assertEqual(main(arguments), 1)
        result = json.loads(output.getvalue())
        export = self.case.root / "public-report"
        arguments = ["qualification", "export", "--catalog", str(self.catalog.root), "--assessment", result["assessment_sha256"], "--output", str(export)]
        with redirect_stdout(io.StringIO()):
            self.assertEqual(main(arguments), 0)
        data = (export / "report.json").read_text()
        self.assertNotIn("unit_sha256", data)
        self.assertNotIn(self.protocol["members"][0]["evaluation_units"][0], data)
        self.assertNotIn("coefficients", data)
        with redirect_stderr(io.StringIO()):
            self.assertEqual(main(arguments), 2)
